package edu.byu.cs.tweeter.client.view.main;

import androidx.lifecycle.ViewModel;

/**
 * Generates a String for displaying on the tabs that have not been implemented yet. This class was
 * generated by the creation of the Tabbed Activity.
 */
public class PageViewModel extends ViewModel {

    private int index = 0;
    private String text = "";

    public void setIndex(int value) {
        index = value;
        text = "Hello world from section: " + index;
    }

    public String getText() {
        return text;
    }
}
